"""add BlacklistedToken model

Revision ID: a60a804bd67a
Revises: 0d55fb19f1ba
Create Date: 2023-02-02 09:57:23.784460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a60a804bd67a"
down_revision = "0d55fb19f1ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
